apiVersion: batch/v1
kind: Job
metadata:
  name: demo-suspend
spec:
  completions: 10
  parallelism: 3
  suspend: true
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: demo
        image: busybox
        command:
        - sleep
        - "60"

